# Generated by Django 5.2 on 2026-02-14 15:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogsection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن بخش'),
        ),
    ]
