# Generated by Django 5.2 on 2026-02-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogsection_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='blog_images/', verbose_name='تصویر اصلی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='introduction',
            field=models.CharField(blank=True, default=' ', max_length=255, verbose_name='مقدمه'),
            preserve_default=False,
        ),
    ]
