# Generated by Django 5.2 on 2026-02-15 21:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_img_alter_blog_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to=blog.models.safe_upload_to),
        ),
    ]
