# Generated by Django 5.2 on 2026-02-10 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان دسته بندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره تماس')),
                ('service', models.CharField(blank=True, max_length=50, null=True, verbose_name='خدمت درخواستی')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='توضیحات')),
                ('doctor', models.CharField(blank=True, max_length=100, verbose_name='پزشک')),
                ('translator', models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم')),
                ('requested_date', models.DateField(verbose_name='تاریخ مورد نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست سرویس',
                'verbose_name_plural': 'درخواست های سرویس',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرویس')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سرویس')),
                ('service_type', models.PositiveSmallIntegerField(choices=[(1, 'TRANSLATOR'), (2, 'DOCTOR'), (3, 'HOTEL'), (4, 'TREATMENT')], default=1, verbose_name='نوع سرویس')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال بودن سرویس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='service.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='service.service', verbose_name='سرویس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فراهم کننده سرویس',
                'verbose_name_plural': 'فراهم کنندگان سرویس',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='کلید گزینه')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار گزینه')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='service.service', verbose_name='سرویس')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='service.serviceprovider', verbose_name='فراهم کننده سرویس')),
            ],
            options={
                'verbose_name': 'گزینه فراهم کننده سرویس',
                'verbose_name_plural': 'گزینه های فراهم کنندگان سرویس',
            },
        ),
    ]
