# Generated by Django 5.2 on 2026-02-13 12:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام نویسنده')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی نویسنده')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='author_profiles/', verbose_name='عکس پروفایل نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('introduction', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدمه')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.blogauthor', verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.blogcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'وبلاگ ها',
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بخش')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن بخش')),
                ('html', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='محتوای HTML')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='تصویر بخش')),
                ('is_main', models.BooleanField(default=False, verbose_name='بخش اصلی')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'بخش وبلاگ',
                'verbose_name_plural': 'بخش های وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام تگ')),
                ('is_main', models.BooleanField(default=False, verbose_name='تگ اصلی')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='blog.blog', verbose_name='مقالات مرتبط')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نظرات',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='RelatedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_blogs', to='blog.blog', verbose_name='مقاله اصلی')),
                ('related_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='blog.blog', verbose_name='مقاله مرتبط')),
            ],
            options={
                'verbose_name': 'مقاله مرتبط',
                'verbose_name_plural': 'مقالات مرتبط',
                'unique_together': {('blog', 'related_blog')},
            },
        ),
    ]
