# Generated by Django 5.2 on 2026-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='time_to_read',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, verbose_name='زمان تقریبی مطالعه (دقیقه)'),
        ),
    ]
