# Generated by Django 5.2 on 2026-02-14 14:48

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='متن بخش'),
        ),
    ]
