# Generated by Django 5.2 on 2026-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='تصویر اصلی'),
        ),
    ]
