# Generated by Django 5.2 on 2026-02-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.blog', verbose_name='مقالات مرتبط'),
        ),
    ]
