# Generated by Django 5.2 on 2026-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogtag_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, default=' ', unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
