# Generated by Django 5.2 on 2026-02-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsection',
            name='html',
        ),
    ]
