# Generated by Django 5.2 on 2026-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogsection_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='blockquote',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مطلب مهم'),
        ),
    ]
