# Generated by Django 5.2 on 2026-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogsection_blockquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='blockquote',
            field=models.TextField(blank=True, null=True, verbose_name='مطلب مهم'),
        ),
    ]
